apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-api
          image: face-detector_auth:latest
          command:
            [
              "sh",
              "-c",
              "/bin/wait-for-it.sh rabbitmq:5672 --timeout=90 -- npm start",
            ]
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: SERVICE
              value: "auth"
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "3001"
            - name: JWT_SECRET
              value: "secret"
            - name: MONGODB_URL
              value: mongodb://user1:uH4*Z89N8Hzy@mongodb:27017/auth
