apiVersion: v1
kind: Service
metadata:
  name: extractor
spec:
  selector:
    app: extractor
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: extractor
  template:
    metadata:
      labels:
        app: extractor
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - extractor
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: extractor-api
          image: face-detector_extractor:latest
          command:
            [
              "sh",
              "-c",
              "/bin/wait-for-it.sh rabbitmq:5672 --timeout=90 -- npm start",
            ]
          volumeMounts:
            - name: aws-credentials
              mountPath: "/home/app/.aws"
              readOnly: true
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          env:
            - name: SERVICE
              value: "extractor"
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "3002"
            - name: JWT_SECRET
              value: "secret"
            - name: MONGODB_URL
              value: mongodb://user2:uH4*Z89N8Hzy@mongodb:27017/faces
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: AWS_BUCKET_NAME
              value: "now-money"
      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-credentials
