apiVersion: v1
kind: Service
metadata:
  name: uploader
spec:
  selector:
    app: uploader
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      containers:
        - name: uploader-api
          image: face-detector_uploader:latest
          command:
            [
              "sh",
              "-c",
              "/bin/wait-for-it.sh rabbitmq:5672 --timeout=120 -- npm start",
            ]
          volumeMounts:
            - name: aws-credentials
              mountPath: "/home/app/.aws"
              readOnly: true
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: SERVICE
              value: "uploader"
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "3003"
            - name: JWT_SECRET
              value: "secret"
            - name: MONGODB_URL
              value: mongodb://user3:uH4*Z89N8Hzy@mongodb:27017/images
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: AWS_BUCKET_NAME
              value: "now-money"
      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-credentials
